import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { AuthProvider } from "./context/AuthContext";

import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <AuthProvider>
            <Header />

            {children}
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}



// import type { Metadata } from 'next';
// import './globals.css';
// import { AuthProvider } from '@/app/context/AuthContext';
// import { Toaster } from 'react-hot-toast';

// import { GoogleOAuthProvider } from '@react-oauth/google';

// export const metadata: Metadata = {
//   title: 'AuthFlow App',
//   description: 'Generated by Firebase Studio',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

//   if (!googleClientId) {
//     console.warn("Google Client ID is not set. Google Login will not work. Please set NEXT_PUBLIC_GOOGLE_CLIENT_ID in your environment variables.");
//   }
  
//   return (
//     <html lang="en">
//       <head>
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
//         <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
//       </head>
//       <body className="font-body antialiased">
//         <GoogleOAuthProvider clientId={googleClientId || "YOUR_GOOGLE_CLIENT_ID_NOT_SET"}>
//           <AuthProvider>
//             {children}
//             <Toaster />
//           </AuthProvider>
//         </GoogleOAuthProvider>
//       </body>
//     </html>
//   );
// }
